---
title: "Data Wrangling"
author: "Sarah Hussain"
date: "3/11/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
all_data <- read_csv("./data.csv")
data_by_artist <- read_csv("./data_by_artist.csv")
data_by_year <- read_csv("./data_by_year.csv")
data_by_genres <- read_csv("./data_by_genres.csv")
data_w_genres <- read_csv("./data_w_genres.csv")
```


```{r}
#changing years to decades 
decade_func <- function(x){ 
  x - (x %% 10)
}
all_data_w_decades <- all_data %>%
  mutate(decade = decade_func(year), 
         decade = as.factor(decade), 
         decade = fct_relevel(decade, "1920"))
```

```{r}
#bin popularity
all_data_w_decades$popularity <- as.factor(all_data_w_decades$popularity)
all_data_w_decades <- all_data_w_decades %>%
  mutate(popularity = fct_collapse(popularity, 
    "0-10" = c("0","1", "2", "3", "4", "5", "6", "7", "8", "9", "10"), 
    "11-20" = c("11", "12", "13", "14", "15", "16", "17", 
            "18", "19", "20"), 
    "21-30" = c("21", "22", "23", "24", "25", "26", "27", 
            "28", "29", "30"), 
    "31-40" = c("31", "32", "33", "34", "35", "36", "37", 
            "38", "39", "40"), 
    "41-50" = c("41", "42", "43", "44", "45", "46", "47", 
            "48", "49", "50"), 
    "51-60" = c("51", "52", "53", "54", "55", "56", "57", 
            "58", "59", "60"), 
    "61-70" = c("61", "62", "63", "64", "65", "66", "67", 
            "68", "69", "70"),
    "71-80" = c("71", "72", "73", "74", "75", "76", "77", 
            "78", "79", "80"),
    "81-90" = c("81", "82", "83", "84", "85", "86", "87", 
            "88", "89", "90"), 
    "91-100" = c("91", "92", "93", "94", "95", "96", "97", 
            "98", "99", "100")
  ), 
  popularity = fct_relevel(popularity, "0-10"))
```

