---
title: "Decision Tree/ Random Forest"
author: "Sarah Hussain"
date: "3/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(tidyr)
library(randomForest)
library(rpart)
library(caret)
library(partykit)
library(readr)
all_data <- read_csv("./data.csv")
data_by_artist <- read_csv("./data_by_artist.csv")
data_by_year <- read_csv("./data_by_year.csv")
data_by_genres <- read_csv("./data_by_genres.csv")
data_w_genres <- read_csv("./data_w_genres.csv")
```

```{r}
#creating test and train data sets 
set.seed(71903948)
n <- nrow(all_data_w_decades)
train_index <- sample(nrow(all_data_w_decades), size=round(.8*n)) #80% training

spotify_train <- all_data_w_decades %>%
  slice(train_index)

spotify_test <- all_data_w_decades %>%
  slice(-train_index)
```

```{r}
ranges <- c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)
metric_range <- data.frame(acousticness = ranges, 
                               danceability = ranges,
                               energy = ranges, 
                               instrumentalness = ranges, 
                               speechiness = ranges, 
                               valence = ranges)

all_combos <- metric_range %>% expand(acousticness, danceability, energy, instrumentalness, speechiness, valence)
```

```{r}
#fitting random forest using decade as the predictor
set.seed(224222)
spotify_rforest <- randomForest(
  decade ~ acousticness + danceability + energy + 
    instrumentalness  + speechiness + valence, 
  data = spotify_train)

#making predictions
decade_results <- all_combos %>%
  mutate(decade_results = predict(spotify_rforest, newdata=all_combos)) 

#write_rds(decade_results, "/Users/ankitsanghi/Desktop/Ankit/Carleton/Classes/STAT 220/content/final-project-sanghi-hussain/decade_results.rds")
```

```{r}
#fitting random forest using popularity as the predictor
set.seed(224202)
spotify_rforest_popularity <- randomForest(
  popularity ~ acousticness + danceability + energy + 
    instrumentalness + speechiness + valence, 
  data = spotify_train)

#making predictions
popularity_results <- predict(spotify_rforest_popularity, newdata=all_combos)
all_results <- mutate(decade_results, popularity_result = popularity_results)

write_rds(all_results, "/Users/ankitsanghi/Desktop/Ankit/Carleton/Classes/STAT 220/content/final-project-sanghi-hussain/results.rds")
```



